# 数据科学/数据处理的流程

## Project name: ds_proj_pd01

文件来源： 此文件出自Python For Beginner学习社群。

作者： 闫小峰

Last Update: 2025-09-17

## 数据处理通用框架/流程模板

[0. 业务理解 Understanding](#0) 

[1. 数据获取和理解 ](#1)
- 数据分析环境设置 Set Up Environment
- 数据获取/采样
- 数据探索  
  - 熟悉数据属性
  - 数据体检： Sanity Checking 

[2. 预处理 Data Preparation](#2)  
- 数据清理  Data Cleaning 
- 数据准备，转换和调整


[3. 数据分析和挖掘 Data Analysis / Data  Mining](#3)
- 传统（经典）数据分析： 
  - 统计学方法 
  - 建模： 业务分析模型
- 机器学习 Machine Learning: 
  - 模型构建: 训练-测试-调试， 
  - 模型预测
- AI增强/辅助型数据分析和开发
  - LLM

[4. 模型评估  Model Evaluation ](#4)


[5. 业务理解/知识深化和提升](#5)
- 数据处理流程自动化 Pipelines
- X by Data Based/Data Driven
   -  Decision Making
   -  Story Line
   -  逻辑论证
   -  发现规律 etc

# 0.业务理解Understanding

- 目标和需求分析：
  - 目的：玩转Pandas！
    - 岗位基本操作训练：学习+练习Pandas基础结构
    - 熟悉使用Pandas读取和输出各种类型的数据（Text，Markdown，HTML，JSON，CSV，XLSX，URL）
    - 敲黑板：重点玩转Pandas的索引操作
    - 学习数据清理的技巧，了解数据清理的灵活度
- 操作执行战术分析：
  - 阶段性要求：
    - 能够实现数据读取自由
    - 进阶：Excel表格的选择读取（职场中的痛点）
    - 没有涵盖：网页爬虫爬取数据
    - 能够灵活处理缺失值和异常值

  - 数据分析需要的方法
  
- 业务理解
  - 暂无

# 1. 数据获取和理解 Get Data & Data Understanding <a id="1"></a>

### 1.1. 数据处理环境设置 Set Up Environment <a id="1.1"></a>

In [3]:
# import modules for data science 
import numpy as np
import pandas as pd

#import module for plotting
import matplotlib.pyplot as plt 
#import rcParams um chinesische Texte richtig in Matplotlib anzuzeigen
from matplotlib import rcParams
# Setze die chin. Schriftart für den Titel, die in Matpolotlib angezeigt werden kann
rcParams['font.family'] = 'SimHei'  # oder 'Microsoft YaHei'

import warnings
warnings.filterwarnings('ignore') #to suppress warning messages


#import pybds_lib as pds

%load_ext autoreload
%autoreload 2
%matplotlib inline

## 1.2.数据获取

### 1.2.1. Pandas读取数据方法总结


Pandas官网不同数据类型的读取存储方法[1]

Reference：  
[1]: https://pandas.pydata.org/docs/reference/io.html

#### 1.2.1. Pandas读取Text数据方法


读取以 txt格式保存的表格数据可以使用：  
pd.read_csv() - Options

>**pandas.`read_csv`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file_path_or_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sep='\t',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encoding=None) <br>

参数说明：  
- file_path_or_buf: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接
- sep: 字符串，指定txt中的分割符. tab: '\t'
- header：整数，指定源文件作为列名的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。默认值：None

In [4]:
try:
    # Try 'latin-1' (ISO-8859-1), a common fallback for text files
    df_list = pd.read_csv('data/contact_person.txt', sep=" ",encoding='latin-1',header=0)
    print("Successfully read with latin-1 encoding.")
except UnicodeDecodeError:
    print("Could not decode with common encodings. Please inspect the file.")

df_list.head()

Successfully read with latin-1 encoding.

     name surname         dob   department
0  George   Brown  12/02/1993  Engineering
1  Andrew   Black  15/04/1975           HR
2   Maria   Green  12/02/1989  Engineering
3   Helen     Fox  21/10/2000    Marketing
4     Joe     Xiu  10/11/1998  Engineering

#### 1.2.2. Pandas读取Markdown数据方法

读取md格式中的表格的概率较小，更常用的场景是将处理好的数据写入Markdown文件中的表格。

pd.to_markdown()方法

#### 1.2.3. Pandas读取HTML数据方法

pd.read_html()方法
- 只能读取网页中的表格(即<table>标签内的数据)    

pd.read_html(io, *[, match, flavor, header, ...])  - options

参数说明：  
- io: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接.注意：网址不接受https
- match: 字符串，正则表达式
- flavor：解释器。默认“lxml”
- header：整数，指定列名所在的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。

In [5]:
url = 'https://en.wikipedia.org/wiki/2020_Summer_Olympics'
medal_table = pd.read_html(url, match='2020 Summer Olympics medal table')

print(medal_table)

URLError: <urlopen error [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte>

In [9]:
import requests

url = 'https://en.wikipedia.org/wiki/2020_Summer_Olympics'
response = requests.get(url).content
response
# html_content = response.text
#df_list = pd.read_html(response, match='2020 Summer Olympics medal table')  
#df_list[0].head()

ProxyError: HTTPSConnectionPool(host='en.wikipedia.org', port=443): Max retries exceeded with url: /wiki/2020_Summer_Olympics (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A0E09D4790>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte')))

#### 1.2.4. Pandas读取JSON数据方法

#### 1.2.5. Pandas读取CSV数据方法

pd.read_csv() - Options

>**pandas.`read_csv`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file_path_or_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sep='',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encoding=None) <br>

参数说明：  
- file_path_or_buf: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接
- sep: 字符串，指定CSV中的分割符
- header：整数，指定源文件作为列名的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。默认值：None

In [7]:
#df=pd.read_csv('data.csv')          # 如果文件与代码文件在同一目录下
#df=pd.read_csv('data/my/data.csv')  # 指定目录
# 使用URL
df=pd.read_csv('https://www.gairuo.com/file/data/dataset/GDP-China.csv')

URLError: <urlopen error [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte>

#### 1.2.6. Pandas读取Excel Table数据方法

pd.read_excel() - Options

>**pandas.`read_excel`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;io,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sheet_name=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;usecols=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nrows=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;true_values=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skiprows=None，<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skipfooter=0，<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;converters=None,<br> 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dtype=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)

参数说明：
- io： 直接使用pd.read_excel(r"文件路径")，默认读取第一个sheet的全部数据。 支持str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
- sheet_name：可选（str, int, list, None, default 0）
  - str: 字符串用于引用的sheet的名称(如果有特定名称)
  - int: 整数用于引用的sheet的隐性索引（从0开始）
  - list：整数和字符串组成的列表，读取后的数据类型是OrderedDict,将列表指定的sheet的数据合并到了一个list中
  - None：表示引用所有sheet （相当于=list（all）的结果）
  - 0： 默认第一个sheet
- header: 表示用第几行作为表头，可选（int, list of int, default 0）
  - 0： 默认，即第一行为表头 
  - int: 跳选第int+1行为表头，前面行数据就被忽略了。行数从0开始
  - [int]：选择列表int指定行的数据作为表头。可用于读取合并行数据做表头
  - None: 不用源表头
- usecols:可选(int, str, list-like, or callable default None)
  - None：默认值，解析所有列。
  - str： 表示Excel列字母。列范围的逗号分隔列表（例如“ A：E”或“ A，C，E：F”）。`范围全闭`。
  - int: 解析到第几列。`对应隐性列索引，从0开始，但是范围全闭（容易让人抓狂的地方）`。 如usecols=3: 选0，1，2，3共4列数据
  - int列表: 解析int对应的那几列。
- index_col：指定列为索引列，可选（int, list of int, default None）
  - 默认为None，即隐性的行作DataFrame的行标签。
  - int: 指定第几列为索引列. 从0开始。
  - list of int：选择列表中的整数列为索引列（多重列索引）
- nrows：（int, default None），指定需要读取前多少行，通常用于较大的数据文件中。注意：从header行下一行开始算！
  - 默认为None
  - int：nrows=3 读取前三行
- skiprows：跳过指定的行，可选（int，list like）
  - int: 跳过前int行=从int+1行开始读取
  - [int]：skiprows=[1,3,5] 跳过第1,3,5行
- dtype: 指定读入的列的数据类型。可选（Type name or dict of column -> type, default None）
  - 默认为None，也就是不改变数据类型
  - 指定列的类型名称或字典。
  - 场景：作用强大，强制限制数据类型，避免后续处理出现意外。如原始字符串数字被当成数值进行运算。可结合df.info先查看各列数据类型是否合乎要求

In [26]:
# 最简单方法： Excel文件无脑读取
df = pd.read_excel("data/simple_tables.xlsx")
df.head()

,Some Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Some Explanation
0,Main Column,January,February,March,April,May,June,July,August,September,October,November,December,NaN,adfasdf adsfasdfsdasdfasdfasdfasdfa
1,Value 1,123,321,312,213,312,222,111,124,0,0,0,0,NaN,NaN
2,Value 2,67,34,56,76,123,545,444,442,0,0,0,0,NaN,1. Explanation 1
3,Value 3,78,23,77,77,222,434,544,234,0,0,0,0,NaN,NaN
4,Value 4,89,12,56,55,33,333,654,423,0,0,0,0,NaN,NaN

In [27]:
# 通常还需要细选某个区域的数据，需要指定行列索引
#
df = pd.read_excel("data/simple_tables.xlsx", header=1, usecols="A:M", nrows=7)
df.head(10)

,Main Column,January,February,March,April,May,June,July,August,September,October,November,December
0,Value 1,123.000000,321.000000,312.000000,213.000000,312.000000,222.000000,111.000000,124.000000,0,0,0,0
1,Value 2,67.000000,34.000000,56.000000,76.000000,123.000000,545.000000,444.000000,442.000000,0,0,0,0
2,Value 3,78.000000,23.000000,77.000000,77.000000,222.000000,434.000000,544.000000,234.000000,0,0,0,0
3,Value 4,89.000000,12.000000,56.000000,55.000000,33.000000,333.000000,654.000000,423.000000,0,0,0,0
4,Value 5,0.491632,0.478972,0.579097,0.638244,0.511928,0.675326,0.606272,0.762846,0,0,0,0
5,Value 6,0.889900,0.920011,0.732506,0.671966,0.616595,0.667848,0.868355,0.276603,0,0,0,0
6,Value 7,0.437504,0.440660,0.424193,0.428878,0.315652,0.451015,0.526459,0.211006,0,0,0,0

In [ ]:
# 复杂的Excel文件（比如多个sheet），可以先获取一些基本信息
# 读取sheet名称
df = pd.ExcelFile("data/complex_tables.xlsx")
df.sheet_names

['Cover page', 'Sheet 1', 'Sheet 2', 'Sheet 3']

In [31]:
# 面对复杂的Excel文件（比如多个sheet），需要指定更多参数
#
df = pd.read_excel("data/complex_tables.xlsx", sheet_name='Sheet 1', header=9, usecols="A,B,D:H", nrows=19)
df.head(10)

       #    Person  Column 4  Column 5  Column 6   Column 7  Column 8
0  123.0  Person 1     15.00     650.0    432.12  6481.8000   9750.00
1  124.0  Person 2     14.50     650.0    432.12  6265.7400   9425.00
2  125.0  Person 3      0.25     555.0    432.12   108.0300    138.75
3  126.0  Person 4      2.12     555.0    432.12   916.0944   1176.60
4  127.0  Person 5      5.64     650.0    432.12  2437.1568   3666.00
5  128.0  Person 6     12.10     400.0    432.12  5228.6520   4840.00
6  129.0  Person 7      3.56     300.0    432.12  1538.3472   1068.00
7    NaN       NaN       NaN       NaN       NaN        NaN       NaN
8    NaN       NaN       NaN       NaN       NaN        NaN       NaN
9    NaN       NaN       NaN       NaN       NaN        NaN       NaN

In [38]:
df_complex = pd.read_excel("data/complex_tables.xlsx", sheet_name=['Sheet 1', 2, 3], header=9, usecols="A,B,D:H", nrows=19)
print(type(df_complex))  # <class 'dict'>
df_complex#['Sheet 1'].head(10)

<class 'dict'>

{'Sheet 1':         #    Person  Column 4  Column 5  Column 6   Column 7  Column 8
 0   123.0  Person 1     15.00     650.0    432.12  6481.8000   9750.00
 1   124.0  Person 2     14.50     650.0    432.12  6265.7400   9425.00
 2   125.0  Person 3      0.25     555.0    432.12   108.0300    138.75
 3   126.0  Person 4      2.12     555.0    432.12   916.0944   1176.60
 4   127.0  Person 5      5.64     650.0    432.12  2437.1568   3666.00
 5   128.0  Person 6     12.10     400.0    432.12  5228.6520   4840.00
 6   129.0  Person 7      3.56     300.0    432.12  1538.3472   1068.00
 7     NaN       NaN       NaN       NaN       NaN        NaN       NaN
 8     NaN       NaN       NaN       NaN       NaN        NaN       NaN
 9     NaN       NaN       NaN       NaN       NaN        NaN       NaN
 10    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 11    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 12    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 13    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 14    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 15    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 16    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 17    NaN       NaN       NaN       NaN       NaN        NaN       NaN
 18    NaN       NaN       NaN       NaN       NaN        NaN      0.00,
 2:         #     Person  Column 4  Column 5  Column 6   Column 7  Column 8
 0   123.0   Person 1     15.00     650.0    432.12  6481.8000   9750.00
 1   124.0   Person 2     14.50     650.0    432.12  6265.7400   9425.00
 2   125.0   Person 3      0.25     555.0    432.12   108.0300    138.75
 3   126.0   Person 4      2.12     555.0    432.12   916.0944   1176.60
 4   127.0   Person 5      5.64     650.0    432.12  2437.1568   3666.00
 5   128.0   Person 6     12.10     400.0    432.12  5228.6520   4840.00
 6   129.0   Person 7      3.56     300.0    432.12  1538.3472   1068.00
 7   130.0   Person 8      6.70     550.0    432.12  2895.2040   3685.00
 8   131.0   Person 9      8.99     651.0    432.12  3884.7588   5852.49
 9   132.0  Person 10     10.25     700.0    432.12  4429.2300   7175.00
 10    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 11    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 12    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 13    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 14    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 15    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 16    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 17    NaN        NaN       NaN       NaN       NaN        NaN       NaN
 18    NaN        NaN       NaN       NaN       NaN        NaN      0.00,
 3:         #     Person  Column 4  Column 5  Column 6    Column 7  Column 8
 0   123.0   Person 1    15.000     650.0    432.12   6481.8000   9750.00
 1   124.0   Person 2    14.500     650.0    432.12   6265.7400   9425.00
 2   125.0   Person 3     0.250     555.0    432.12    108.0300    138.75
 3   126.0   Person 4     2.120     555.0    432.12    916.0944   1176.60
 4   127.0   Person 5     5.640     650.0    432.12   2437.1568   3666.00
 5   128.0   Person 6    12.100     400.0    432.12   5228.6520   4840.00
 6   129.0   Person 7     3.560     300.0    432.12   1538.3472   1068.00
 7   130.0   Person 8    11.450     450.0    432.12   4947.7740   5152.50
 8   131.0   Person 9    22.320     550.0    432.12   9644.9184  12276.00
 9   132.0  Person 10    20.180     425.0    432.12   8720.1816   8576.50
 10  133.0  Person 11    32.000     375.0    432.12  13827.8400  12000.00
 11  134.0  Person 12     5.570     650.0    432.12   2406.9084   3620.50
 12  135.0  Person 13     8.875     750.0    444.00   3940.5000   6656.25
 13  136.0  Person 14     3.250     555.0    432.12   1404.3900   1803.75
 14  137.0  Person 15    12.230     475.0    432.12   5284.8276   5809.25
 15  138.0  Person 16     0.330     650.0    575.00    189.7500    214.50
 16  139.0  Person 17     2.750     123.0    432.12   1188.3300    338.25
 17    NaN        NaN       NaN       NaN       NaN         NaN       NaN
 18    NaN        NaN       NaN       NaN       NaN         NaN      0.00}

## 1.3.数据探索和理解

### 1.3.1. 熟悉数据属性
→ 数据属性类型

步骤：
- 熟悉数据属性：
  - 抽样查看数据。方法：
    - df.head(n):查看首个(n)行数据
    - df.tail(n)：查看最后(n)行数据
    - df.sample(n)： 随机查看（n）行数据
  - 检查数据基本信息/类型和形状. 方法：
    - df.info: 显示所有数据的类型、索引情况、行列数、各字段数据类型、内存占用等。注意：Series不支持
    - df.dtype: 返回每个字段的数据类型及DataFrame整体的类型
    - df.shape:  返回一个set（行数，列数）。注意：不包含索引。Series结构：列数为空
- 数据检测 （Sanity Check）
  - df.describe()： 返回df数据的统计信息（表格形式），每一行对应一个统计指标，如总数、均值、标准差、最小值、四分位数、最大值等。

## 2. 数据预处理 Data Preparation  <a id="2"></a>

好数据的评估指标：准确，完整，一致，可调用，合规

必要流程：
- 数据清洗（Data Cleaning）
  - 缺失值
  - （异常值发现和处理）
- 数据准备：  
- 数据转换
- 数据调整

### 2.1 掌握Pandas索引

#### 2.1.1 Pandas数据的索引操作

基础知识点和必备技能：
 - 了解Pandas索引的种类
 - 索引的构建（包含）
 - 索引的重建（保留/覆盖原索引）

#### 2.1.2 通过操作索引来操作Pandas数据

基础知识点和必备技能：
- 用索引来筛选数据

## 3. 数据分析和探索，建模  Data Analysis & Data  Mining，Modelling <a id="3"></a>

方法：
1. 统计学分析
   1. 发现和处理异常值
2. 行业领域分析
3. 分析结果可视化

### 基于数据的建模

我们可以思考如何从现有的数据中提取更具有价值的信息，通常的方法就是建立一些自己的观点=模型，再验证。

在第一个Python学习项目中，我们可以思考如下：
- 建立用户年龄和购买关系的模型：
  - 假设：销售额和用户年龄相关 → 建立一个用户年龄和销售额的关系模型 →通过数学解析或图解法求得该关系 → 验证自己的假设是否属实（证实或证伪）
- 建立一个用户年龄和区域的关系： → 自己尝试
  - 假设：不同区域的人群拥有某个显性的购买趋向 → 建立一个用户年龄和地域的关系模型 → 通过数学解析或图解法求得对应关系 → 验证假设

### 数据可视化

了解和学习使用画图专业户matplotlib

## 4. 模型评估 Model Evaluation <a id="4"></a>

## 5. 业务理解/知识深化和提升  <a id="5"></a> 

总结：
项目目标: 通过实际案例学习和熟悉Pandas的读取最常见数据类型的方法，基础操作。

练习步骤：


学习体会和反馈？？